# Generated by Django 4.2.9 on 2024-02-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSTR_pereval_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perevaladded',
            options={'verbose_name_plural': 'Данные перевалов'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
